<!DOCTYPE html>
<?php

include('db.php');
    $special=mysql_query ("select * from men_special");
	$snacks=mysql_query ("select * from menu_snacks");
    $starters=mysql_query ("select * from menu_starters");
    $soups=mysql_query ("select * from menu_soups");
    $drinks=mysql_query ("select * from menu_drinks");
    $desserts=mysql_query ("select * from menu_desserts");
    $main=mysql_query ("select * from menu_main");
    
?>

<?php 
session_start();
?>
<?php
$u=$_SESSION['uname'];
$p=$_SESSION['pwd'];
?>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body style="padding:0px; margin:0px; background-color:#fff;font-family:Arial, sans-serif" background="bg/666.jpg">
<div>
<ul class="horizontalul">
   <li><a class="active" href="home2.php">Home</a></li>
   <li><a href="Menu2.php">Menu</a>
   <ul>
   <li ><a href="special.php">Specialities</li>
    <li ><a   href="Snacks.php">Snacks</li>
   <li ><a  href="Soups.php">Soups</li>
   <li ><a  href="Starters.php">Starters</li>
   <li ><a  href="MainCourse.php">Main Course</li>
   <li ><a  href="Desserts.php">Desserts</li>
   <li ><a  href="Drinks.php">Drinks</li>
   </ul>
   <li><a href="gallery2.php">Gallery</a></li>
    <li><a href="profile.php">My Account</a></li>

   <li><a href="order2.php">Order Online</a></li>
   <li><a href="contact2.php">Contact</a></li>
   <li><a href="about2.php">About us</a></li>
</ul> 
</div>


    <!-- #region Jssor Slider Begin -->

    <!-- Generated by Jssor Slider Maker. -->
    <!-- This demo works without jquery library. -->

    <script type="text/javascript" src="js/jssor.slider.min.js"></script>
    <!-- use jssor.slider.debug.js instead for debug -->
    <script>
        jssor_1_slider_init = function() {
            
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,$Opacity:2}
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 600);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            //responsive code end
        };
    </script>

    <style>
        
        /* jssor slider bullet navigator skin 05 css */
        /*
        .jssorb05 div           (normal)
        .jssorb05 div:hover     (normal mouseover)
        .jssorb05 .av           (active)
        .jssorb05 .av:hover     (active mouseover)
        .jssorb05 .dn           (mousedown)
        */
        .jssorb05 {
            position: absolute;
        }
        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
            position: absolute;
            /* size of bullet elment */
            width: 16px;
            height: 16px;
            background: url('img/b05.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb05 div { background-position: -7px -7px; }
        .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
        .jssorb05 .av { background-position: -67px -7px; }
        .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }

        /* jssor slider arrow navigator skin 12 css */
        /*
        .jssora12l                  (normal)
        .jssora12r                  (normal)
        .jssora12l:hover            (normal mouseover)
        .jssora12r:hover            (normal mouseover)
        .jssora12l.jssora12ldn      (mousedown)
        .jssora12r.jssora12rdn      (mousedown)
        */
        .jssora12l, .jssora12r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 30px;
            height: 46px;
            cursor: pointer;
            background: url('img/a12.png') no-repeat;
            overflow: hidden;
        }
        .jssora12l { background-position: -16px -37px; }
        .jssora12r { background-position: -75px -37px; }
        .jssora12l:hover { background-position: -136px -37px; }
        .jssora12r:hover { background-position: -195px -37px; }
        .jssora12l.jssora12ldn { background-position: -256px -37px; }
        .jssora12r.jssora12rdn { background-position: -315px -37px; }
    </style>


    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
       <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/11.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/22.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/33.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/44.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/55.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/66.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/77.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/88.jpg" />
            </div>
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="menu/99.jpg" />
            </div>
            
			<a data-u="ad" href="http://www.jssor.com" style="display:none">Responsive Slider</a>
        
        </div>
         <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
            <!-- bullet navigator item prototype -->
            <div data-u="prototype" style="width:16px;height:16px;"></div>
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora12l" style="top:0px;left:0px;width:30px;height:46px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora12r" style="top:0px;right:0px;width:30px;height:46px;" data-autocenter="2"></span>
    </div>
    <script>
        jssor_1_slider_init();
    </script>

    <!-- #endregion Jssor Slider End -->
</style>
</head>
<body>
<!special>
<h2 style="text-align:center">Today'S Special</h2>
<?php
while($row=mysql_fetch_object($special))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<!Soups>

<div>
<h2 style="text-align:center">Soups</h2>
<?php
while($row=mysql_fetch_object($soups))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<!Starters>

<div>
<h2 style="text-align:center">Starters</h2>
<?php
while($row=mysql_fetch_object($starters))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>
</div>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<!snacks>

<div>
<h2 style="text-align:center">Snacks</h2>
<?php
while($row=mysql_fetch_object($snacks))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>
</div>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<!desserts>

<div>
<h2 style="text-align:center">Desserts</h2>
<?php
while($row=mysql_fetch_object($desserts))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>
</div>
<div class="clearfix"></div>

<!-- The Modal -->
<div id="myModal" class="modal">
  <span class="close">×</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>


<br><br><br><br><br><br>
<!Drinks>

<div>
<h2 style="text-align:center">Drinks</h2>
<?php
while($row=mysql_fetch_object($drinks))
					  {
 ?>

<div class="responsive">
  <div class="img">
      <img src="<?php echo'upload/'.$row->item ?>" alt="<?php echo $row->name ?>" width="300" height="200">
    <div class="desc"><?php echo $row->name ?></div>
  </div>
</div>
<?php
}
?>
</div>
</body>
</html>
<style type="text/css">
div#header {
    background-color: darkgoldenrod;
    text-align: -webkit-center;
    color: beige;
    padding: 0%;
	}
ul
{
height:7%;

list-style-type:none;
margin: 0;
padding :0;
overflow:hidden;
background;
position:none;
top:100%;
width:100%
}
li
{
float:left;

}
li:last-child
{
float:left;
border-right:none;
}
li a{
display:block;
color:white;
text-align:center;
padding:14px 16px;
text-decoration:;
}
li a:hover
{
a:active
{
background-color:#111
};
background-color:	#FF0000 ;
}

	p.one 
{
border-style:solid;
border-width:5px;
}
frameset.two 
{
border-style:solid;
border-width:medium;
}
a {
color:white; 
text-decoration:none }

p.three
{
border-style:solid;
border-width:1px;
}
li ul { margin:0; padding:0 5px; line-height:none;height:42%;
 position:absolute; top:29px; left:0; border:solid 1px #c93300; border-width:0px 1px 1px 1px; width:180px; display:none; background:#FFFFFF;}
li:hover ul { display:block }
li:hover a {color:white; background::#4CAF50;
}
li ul li { display:block;  border-bottom:solid 3px #888888 ; width:100%; background:url(images/d_horizontal_red_classic_menu_arrow.gif) no-repeat 3px 12px; padding:10px 2px  10px; }
li ul li:last-child { border-bottom:0px;}
li ul a { border-width:10px; color:#909090; padding:0 5px 0 0; background-color:transparent;}
li:hover ul li a { color:#909090}
li ul li a:hover {color:white; background::#4CAF50;
}
 }
/* The Image Box */
div.img {
    border: 1px solid #ccc;
}

div.img:hover {
    border: 1px solid #777;
}

/* The Image */
div.img img {
    width: 100%;
    height: auto;
    cursor: pointer;
}

/* Description of Image */
div.desc {
    padding: 15px;
    text-align: center;
	color: white;
}

* {
    box-sizing: border-box;
}

/* Add Responsiveness */
.responsive {
    padding: 0 6px;
    float: left;
    width: 24.99999%;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
}

/* Caption of Modal Image */
#caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
}

/* Add Animation */
.modal-content, #caption {    
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
    from {transform:scale(0)} 
    to {transform:scale(1)}
}

@keyframes zoom {
    from {transform:scale(0.1)} 
    to {transform:scale(1)}
}

/* The Close Button */
.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}

/* Responsive Columns */
@media only screen and (max-width: 700px){
    .responsive {
        width: 49.99999%;
        margin: 6px 0;
    }
    .modal-content {
        width: 100%;
    }
}

@media only screen and (max-width: 500px){
    .responsive {
        width: 100%;
    }
}

/* Clear Floats */
.clearfix:after {
    content: "";
    display: table;
    clear: both;
}
</style>

<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
    modal.style.display = "none";
}

// Get all images and insert the clicked image inside the modal
// Get the content of the image description and insert it inside the modal image caption
var images = document.getElementsByTagName('img');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
var i;
for (i = 0; i < images.length; i++) {
   images[i].onclick = function(){
       modal.style.display = "block";
       modalImg.src = this.src;
       modalImg.alt = this.alt;
       captionText.innerHTML = this.nextElementSibling.innerHTML;
   }
}
</script>

</style>

